// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(TesteContext))]
    [Migration("20231223185620_Produto")]
    partial class Produto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CnpjFornecedor")
                        .IsRequired()
                        .HasColumnName("CnpjFornecedor")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CodigoFornecedor")
                        .IsRequired()
                        .HasColumnName("CodigoFornecedor")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnName("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnName("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoFornecedor")
                        .IsRequired()
                        .HasColumnName("DescricaoFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnName("DescricaoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Situacao")
                        .HasColumnName("Situacao")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
